/**
 * API per gestione Kerberos: stato ticket, setup krb5.conf, kinit, test WinRM.
 * GET  → stato attuale (ticket valido, krb5.conf presente, realm)
 * POST → azione: "setup" | "kinit" | "test-winrm"
 */

import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/api-auth";
import { withTenantFromSession } from "@/lib/api-tenant";
import { getAdRealm, getAdIntegrationById } from "@/lib/db";
import { decrypt } from "@/lib/crypto";
import { execFile, spawn } from "child_process";
import { promisify } from "util";
import fs from "fs";
import os from "os";
import path from "path";

const execFileAsync = promisify(execFile);

function runKinit(principal: string, password: string): Promise<{ success: boolean; stderr: string }> {
  return new Promise((resolve) => {
    const proc = spawn("kinit", [principal], {
      stdio: ["pipe", "pipe", "pipe"],
      timeout: 15000,
    });
    let stderr = "";
    proc.stderr.on("data", (d: Buffer) => { stderr += d.toString(); });
    proc.stdout.on("data", () => { /* ignore */ });
    proc.on("close", (code) => {
      resolve({ success: code === 0, stderr: stderr.trim() });
    });
    proc.on("error", (err) => {
      resolve({ success: false, stderr: err.message });
    });
    proc.stdin.write(password + "\n");
    proc.stdin.end();
  });
}

async function getKerberosStatus(): Promise<{
  hasKrb5Conf: boolean;
  krb5ConfPath: string | null;
  hasTicket: boolean;
  ticketPrincipal: string | null;
  ticketExpires: string | null;
  realm: string | null;
  dcHost: string | null;
  platform: string;
}> {
  const adInfo = getAdRealm();
  const result = {
    hasKrb5Conf: false,
    krb5ConfPath: null as string | null,
    hasTicket: false,
    ticketPrincipal: null as string | null,
    ticketExpires: null as string | null,
    realm: adInfo?.realm || null,
    dcHost: adInfo?.dcHost || null,
    platform: process.platform,
  };

  // Check krb5.conf
  const userConf = path.join(os.homedir(), ".krb5.conf");
  const systemConf = "/etc/krb5.conf";
  const envConf = process.env.KRB5_CONFIG || "";

  for (const confPath of [envConf, systemConf, userConf]) {
    if (confPath && fs.existsSync(confPath)) {
      try {
        const content = fs.readFileSync(confPath, "utf-8");
        if (adInfo?.realm && content.toUpperCase().includes(adInfo.realm.toUpperCase())) {
          result.hasKrb5Conf = true;
          result.krb5ConfPath = confPath;
          break;
        }
      } catch { /* skip */ }
    }
  }

  // Check klist
  try {
    const { stdout } = await execFileAsync("klist", [], { timeout: 5000 });
    if (stdout.toLowerCase().includes("krbtgt")) {
      result.hasTicket = true;
      // Parse principal
      const principalMatch = stdout.match(/Default principal:\s*(.+)/i);
      if (principalMatch) {
        result.ticketPrincipal = principalMatch[1].trim();
      }
      // Parse expiry
      const expiryMatch = stdout.match(/(\d{2}\/\d{2}\/\d{4}\s+\d{2}:\d{2}:\d{2})/);
      if (expiryMatch) {
        result.ticketExpires = expiryMatch[1];
      }
    }
  } catch { /* no ticket */ }

  return result;
}

export async function GET() {
  return withTenantFromSession(async () => {
    try {
      const status = await getKerberosStatus();
      return NextResponse.json(status);
    } catch (e) {
      return NextResponse.json(
        { error: e instanceof Error ? e.message : "Errore verifica Kerberos" },
        { status: 500 }
      );
    }
  });
}

export async function POST(request: Request) {
  return withTenantFromSession(async () => {
    const admin = await requireAdmin();
    if (admin instanceof NextResponse) return admin;

    let body: Record<string, unknown>;
  try {
    body = await request.json() as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: "Body JSON non valido" }, { status: 400 });
  }

  const action = String(body.action || "");
  const integrationId = typeof body.integrationId === "number" ? body.integrationId : null;

  if (action === "setup") {
    // Setup krb5.conf dal dominio AD
    const adInfo = getAdRealm();
    if (!adInfo) {
      return NextResponse.json({ error: "Nessuna integrazione AD configurata" }, { status: 400 });
    }

    const realm = adInfo.realm.toUpperCase();
    const realmLower = adInfo.realm.toLowerCase();
    const dcHost = adInfo.dcHost;

    const krb5Content = `# Auto-generated by DA-INVENT for WinRM Kerberos auth
[libdefaults]
    default_realm = ${realm}
    dns_lookup_realm = false
    dns_lookup_kdc = true
    forwardable = true
    rdns = false
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
    permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac

[realms]
    ${realm} = {
        kdc = ${dcHost}
        admin_server = ${dcHost}
        default_domain = ${realmLower}
    }

[domain_realm]
    .${realmLower} = ${realm}
    ${realmLower} = ${realm}
`;

    let confPath = "/etc/krb5.conf";
    try {
      fs.writeFileSync(confPath, krb5Content);
    } catch {
      // Fallback a user home
      confPath = path.join(os.homedir(), ".krb5.conf");
      try {
        fs.writeFileSync(confPath, krb5Content);
        process.env.KRB5_CONFIG = confPath;
      } catch (e) {
        return NextResponse.json(
          { error: `Impossibile scrivere krb5.conf: ${e instanceof Error ? e.message : String(e)}` },
          { status: 500 }
        );
      }
    }

    return NextResponse.json({ success: true, path: confPath, realm });
  }

  if (action === "kinit") {
    // Esegui kinit con le credenziali dell'integrazione AD
    if (!integrationId) {
      return NextResponse.json({ error: "integrationId richiesto" }, { status: 400 });
    }

    const integration = getAdIntegrationById(integrationId);
    if (!integration) {
      return NextResponse.json({ error: "Integrazione non trovata" }, { status: 404 });
    }

    const username = decrypt(integration.encrypted_username);
    const password = decrypt(integration.encrypted_password);
    const realm = integration.domain.toUpperCase();

    // Costruisci principal
    let principal = username;
    if (!username.includes("@")) {
      if (username.includes("\\")) {
        principal = username.split("\\")[1] + "@" + realm;
      } else {
        principal = username + "@" + realm;
      }
    }

    try {
      const kinitResult = await runKinit(principal, password);

      if (!kinitResult.success) {
        let hint = "";
        const msg = kinitResult.stderr;
        if (msg.includes("Cannot contact")) {
          hint = " — Verifica che il DC sia raggiungibile sulla porta 88 (Kerberos).";
        } else if (msg.includes("Preauthentication failed") || msg.includes("Client not found")) {
          hint = " — Username o password errati, oppure il formato deve essere user@DOMAIN.FQDN.";
        }
        return NextResponse.json({ success: false, error: (msg || "kinit fallito") + hint });
      }

      // Verifica con klist
      const { stdout: klistOut } = await execFileAsync("klist", [], { timeout: 5000 });
      const hasTicket = klistOut.toLowerCase().includes("krbtgt");

      if (!hasTicket) {
        return NextResponse.json({
          success: false,
          error: `kinit completato ma nessun ticket ottenuto.`,
        });
      }

      return NextResponse.json({ success: true, principal, message: "Ticket Kerberos ottenuto" });
    } catch (e) {
      return NextResponse.json({
        success: false,
        error: e instanceof Error ? e.message : "Errore kinit",
      });
    }
  }

  if (action === "test-winrm") {
    // Test WinRM via Kerberos verso un host specifico
    const host = String(body.host || "");
    if (!host) {
      return NextResponse.json({ error: "host richiesto" }, { status: 400 });
    }

    if (!integrationId) {
      return NextResponse.json({ error: "integrationId richiesto" }, { status: 400 });
    }

    const integration = getAdIntegrationById(integrationId);
    if (!integration) {
      return NextResponse.json({ error: "Integrazione non trovata" }, { status: 404 });
    }

    const username = decrypt(integration.encrypted_username);
    const password = decrypt(integration.encrypted_password);
    const port = typeof body.port === "number" ? body.port : 5985;

    try {
      const { runWinrmCommand } = await import("@/lib/devices/winrm-run");
      const output = await runWinrmCommand(host, port, username, password, "hostname", false, integration.domain);
      return NextResponse.json({
        success: true,
        hostname: output.trim(),
        message: `WinRM OK: ${output.trim()}`,
      });
    } catch (e) {
      return NextResponse.json({
        success: false,
        error: e instanceof Error ? e.message : "Test WinRM fallito",
      });
    }
  }

  return NextResponse.json({ error: `Azione non valida: ${action}` }, { status: 400 });
  });
}
