#!/usr/bin/env python3
"""
Bridge Python per WinRM: riceve comandi via stdin JSON, esegue via pywinrm, restituisce stdout JSON.

Catena di trasporto automatica: Kerberos → NTLM → CredSSP → Basic
- Kerberos: richiede krb5.conf + ticket valido (kinit). Auto-kinit se username+password forniti.
- NTLM: funziona su HTTP con SPNEGO session encryption (pyspnego + requests-ntlm).
- CredSSP: fallback se NTLM rifiutato e CredSSP abilitato sul target.
- Basic: ultimo tentativo, richiede AllowUnencrypted=true sul target.

Input JSON (stdin):
  host, port, username, password, command, usePowershell, realm (opzionale)

Variabile env: WINRM_TRANSPORT=kerberos|ntlm|credssp|basic (default: auto)
"""
import json
import sys
import base64
import os
import subprocess
import shutil
import platform


def run_large_ps(session, script):
    """Execute large PowerShell scripts that exceed cmd.exe's 8191 char limit.
    Writes base64 chunks to a temp file on the target, then decodes and executes."""
    encoded = base64.b64encode(script.encode("utf_16_le")).decode("ascii")
    cmd_line_len = len(f"powershell -encodedcommand {encoded}")

    if cmd_line_len <= 7500:
        return session.run_ps(script)

    temp_id = f"da-invent-{os.getpid()}"
    b64_file = f"C:\\Windows\\Temp\\{temp_id}.b64"

    chunk_size = 6000
    for i in range(0, len(encoded), chunk_size):
        chunk = encoded[i:i + chunk_size]
        redir = ">" if i == 0 else ">>"
        session.run_cmd(f"echo {chunk}{redir}{b64_file}")

    exec_script = (
        f"$b=[IO.File]::ReadAllText('{b64_file}').Trim();"
        f"$clean=$b -replace '[\\r\\n\\s]','';"
        f"$bytes=[Convert]::FromBase64String($clean);"
        f"$s=[Text.Encoding]::Unicode.GetString($bytes);"
        f"Remove-Item '{b64_file}' -Force -EA 0;"
        f"Invoke-Expression $s"
    )
    return session.run_ps(exec_script)


# ═══════════════════════════════════════════════════════════════
# Kerberos helpers
# ═══════════════════════════════════════════════════════════════

def _has_valid_ticket(principal: str = "") -> bool:
    """Check if there's a valid Kerberos ticket (not expired)."""
    klist = shutil.which("klist")
    if not klist:
        return False
    try:
        result = subprocess.run([klist], capture_output=True, text=True, timeout=5)
        if result.returncode != 0:
            return False
        # Se specificato, verifica che il ticket sia per il principal giusto
        if principal:
            return principal.lower() in result.stdout.lower()
        return "krbtgt" in result.stdout.lower()
    except Exception:
        return False


def _auto_kinit(username: str, password: str, realm: str = "") -> bool:
    """Esegue kinit automatico. Restituisce True se il ticket è stato ottenuto."""
    kinit = shutil.which("kinit")
    if not kinit:
        return False

    # Costruisci il principal: user@REALM
    principal = username
    if realm and "@" not in username:
        principal = f"{username}@{realm.upper()}"
    elif "\\" in username:
        # DOMAIN\user → user@DOMAIN
        parts = username.split("\\", 1)
        domain = parts[0].upper()
        user = parts[1]
        if realm:
            principal = f"{user}@{realm.upper()}"
        else:
            principal = f"{user}@{domain}"

    # Già un ticket valido per questo principal?
    if _has_valid_ticket(principal):
        return True

    try:
        proc = subprocess.run(
            [kinit, principal],
            input=password + "\n",
            capture_output=True,
            text=True,
            timeout=15,
        )
        return proc.returncode == 0
    except Exception:
        return False


def _ensure_krb5_conf(realm: str, dc_host: str) -> bool:
    """Crea o aggiorna /etc/krb5.conf se mancante o non contiene il realm.
    Su macOS/Linux senza permessi root, scrive in ~/.krb5.conf e setta KRB5_CONFIG."""
    if not realm or not dc_host:
        return False

    realm_upper = realm.upper()
    realm_lower = realm.lower()

    # Controlla se esiste già un krb5.conf funzionante col nostro realm
    system_conf = "/etc/krb5.conf"
    user_conf = os.path.expanduser("~/.krb5.conf")
    env_conf = os.environ.get("KRB5_CONFIG", "")

    for conf_path in [env_conf, system_conf, user_conf]:
        if conf_path and os.path.isfile(conf_path):
            try:
                with open(conf_path, "r") as f:
                    content = f.read()
                if realm_upper in content:
                    # Realm già configurato, assicuriamoci che KRB5_CONFIG punti qui
                    if conf_path != system_conf:
                        os.environ["KRB5_CONFIG"] = conf_path
                    return True
            except Exception:
                pass

    # Genera configurazione
    krb5_content = f"""# Auto-generated by DA-INVENT for WinRM Kerberos auth
[libdefaults]
    default_realm = {realm_upper}
    dns_lookup_realm = false
    dns_lookup_kdc = true
    forwardable = true
    rdns = false
    # Abilita encryption types compatibili con AD
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
    permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac

[realms]
    {realm_upper} = {{
        kdc = {dc_host}
        admin_server = {dc_host}
        default_domain = {realm_lower}
    }}

[domain_realm]
    .{realm_lower} = {realm_upper}
    {realm_lower} = {realm_upper}
"""

    # Prova a scrivere in /etc/krb5.conf (richiede root), altrimenti in ~/.krb5.conf
    try:
        with open(system_conf, "w") as f:
            f.write(krb5_content)
        return True
    except PermissionError:
        pass

    try:
        with open(user_conf, "w") as f:
            f.write(krb5_content)
        os.environ["KRB5_CONFIG"] = user_conf
        return True
    except Exception:
        return False


# ═══════════════════════════════════════════════════════════════
# Error detection helpers
# ═══════════════════════════════════════════════════════════════

def _is_cred_rejection(error_msg: str) -> bool:
    err_lower = error_msg.lower()
    return (
        "401" in error_msg
        or "credentials were rejected" in err_lower
        or "authorization failed" in err_lower
        or "access is denied" in err_lower
        or "logon failure" in err_lower
    )


def _is_kerberos_failure(error_msg: str) -> bool:
    """Detect Kerberos-specific failures (missing ticket, KDC unreachable, etc.)."""
    err_lower = error_msg.lower()
    return (
        "kerberos" in err_lower
        or "kinit" in err_lower
        or "kdc" in err_lower
        or "gss" in err_lower
        or "spnego" in err_lower
        or "no credentials" in err_lower
        or "ticket" in err_lower
    )


def _is_credssp_unavailable(error_msg: str) -> bool:
    """Detect when server advertises only Negotiate/Kerberos and does not offer CredSSP."""
    err_lower = error_msg.lower()
    return (
        "did not response credssp" in err_lower
        or "credssp being an available" in err_lower
        or ("negotiate" in err_lower and "kerberos" in err_lower)
    )


def _is_basic_unavailable(error_msg: str) -> bool:
    """Detect when Basic auth is rejected (AllowUnencrypted=false or Basic not enabled)."""
    err_lower = error_msg.lower()
    return (
        "basic" in err_lower and ("not allowed" in err_lower or "disabled" in err_lower or "401" in err_lower)
    )


def _windows_winrm_config_hint() -> str:
    return (
        "\n\nComandi PowerShell (Admin) per abilitare WinRM sul Windows target:\n"
        "  # Opzione A — Kerberos (consigliato, DA-INVENT esegue kinit automatico):\n"
        "  winrm quickconfig -force\n"
        "  # Nessuna modifica necessaria: Kerberos è abilitato per default.\n"
        "  # Verifica: winrm get winrm/config/service/auth → Negotiate=true\n\n"
        "  # Opzione B — NTLM (se NTLM non è bloccato da GPO):\n"
        "  winrm quickconfig -force\n"
        "  Set-Item WSMan:\\localhost\\Service\\Auth\\Negotiate $true\n"
        "  # Se bloccato da GPO: secpol.msc → Criteri locali → Opzioni di sicurezza →\n"
        "  #   'Sicurezza di rete: limita NTLM: traffico NTLM in entrata' → Consenti tutto\n\n"
        "  # Opzione C — Basic auth (trasmette credenziali in chiaro, NON raccomandato):\n"
        "  Set-Item WSMan:\\localhost\\Service\\Auth\\Basic $true\n"
        "  Set-Item WSMan:\\localhost\\Service\\AllowUnencrypted $true\n"
        "  Restart-Service WinRM\n"
    )


# ═══════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════

def main():
    raw = sys.stdin.read()
    try:
        req = json.loads(raw)
    except Exception as e:
        print(json.dumps({"error": f"JSON parse error: {e}"}))
        sys.exit(1)

    host = req.get("host", "")
    port = req.get("port", 5985)
    username = req.get("username", "")
    password = req.get("password", "")
    command = req.get("command", "")
    use_powershell = req.get("usePowershell", False)
    realm = req.get("realm", "")

    protocol = "https" if port == 5986 else "http"
    endpoint = f"{protocol}://{host}:{port}/wsman"

    try:
        import winrm  # noqa: F401
    except ImportError as e:
        print(
            json.dumps(
                {
                    "error": (
                        "Modulo Python pywinrm assente: "
                        + str(e)
                        + ". Sul server DA-INVENT: python3 -m venv ~/.da-invent-venv && "
                        "~/.da-invent-venv/bin/pip install pywinrm requests-ntlm requests-credssp "
                        "oppure reinstalla con scripts/install.sh. Imposta WINRM_PYTHON se usi un altro interprete."
                    )
                }
            )
        )
        sys.exit(1)

    def run_session(transport: str):
        s = winrm.Session(
            endpoint,
            auth=(username, password),
            transport=transport,
            server_cert_validation="ignore",
            read_timeout_sec=120,
        )
        if use_powershell:
            return run_large_ps(s, command)
        return s.run_cmd(command)

    winrm_transport_env = os.environ.get("WINRM_TRANSPORT", "").strip().lower()
    last_error = ""
    tried = []

    # ── Kerberos pre-flight: setup krb5.conf e kinit ──
    kerberos_ready = False
    if winrm_transport_env in ("", "kerberos"):
        # Determina realm: esplicito > estratto da username (user@domain) > parametro
        effective_realm = realm
        if not effective_realm and "@" in username:
            effective_realm = username.split("@", 1)[1]
        elif not effective_realm and "\\" in username:
            effective_realm = username.split("\\", 1)[0]

        if effective_realm:
            _ensure_krb5_conf(effective_realm, host)
            kerberos_ready = _auto_kinit(username, password, effective_realm)

    try:
        if winrm_transport_env in ("ntlm", "credssp", "basic", "kerberos"):
            # Trasporto forzato dall'utente
            if winrm_transport_env == "kerberos" and not kerberos_ready:
                raise Exception(
                    "Kerberos richiesto ma kinit fallito. Verifica username (user@DOMAIN.FQDN), "
                    "password e che il DC sia raggiungibile."
                )
            tried.append(winrm_transport_env)
            r = run_session(winrm_transport_env)
        else:
            # ── Catena automatica: Kerberos → NTLM → CredSSP → Basic ──
            r = None
            chain_error = None

            # 1. Kerberos (se ticket disponibile)
            if kerberos_ready:
                try:
                    tried.append("kerberos")
                    r = run_session("kerberos")
                except Exception as ke:
                    chain_error = str(ke)
                    last_error = chain_error
                    # Kerberos fallito, continua con NTLM

            # 2. NTLM
            if r is None:
                try:
                    tried.append("ntlm")
                    r = run_session("ntlm")
                    chain_error = None
                except Exception as ne:
                    chain_error = str(ne)
                    last_error = chain_error

                    # 3. CredSSP (se NTLM rifiutato)
                    if _is_cred_rejection(chain_error):
                        try:
                            tried.append("credssp")
                            r = run_session("credssp")
                            chain_error = None
                        except (ImportError, ModuleNotFoundError) as ie:
                            last_error = f"NTLM rifiutato; CredSSP non disponibile: {ie}"
                        except Exception as ce:
                            last_error = str(ce)
                            if _is_credssp_unavailable(last_error):
                                # 4. Basic (ultimo tentativo)
                                try:
                                    tried.append("basic")
                                    r = run_session("basic")
                                    chain_error = None
                                except Exception as be:
                                    last_error = str(be)
                            else:
                                chain_error = last_error
                    elif _is_credssp_unavailable(chain_error):
                        # Server Kerberos-only e il nostro Kerberos non ha funzionato → Basic
                        try:
                            tried.append("basic")
                            r = run_session("basic")
                            chain_error = None
                        except Exception as be:
                            last_error = str(be)

            if r is None:
                raise Exception(last_error or "Tutti i metodi di autenticazione falliti")

        stdout = r.std_out.decode("utf-8", errors="replace") if r.std_out else ""
        stderr = r.std_err.decode("utf-8", errors="replace") if r.std_err else ""

        print(json.dumps({
            "stdout": stdout,
            "stderr": stderr,
            "exitCode": r.status_code,
            "transport": tried[-1] if tried else "unknown",
        }))

    except Exception as e:
        error_msg = str(e)
        err_lower = error_msg.lower()
        tried_str = " → ".join(tried) if tried else "nessuno"

        if _is_kerberos_failure(error_msg) and not any(t != "kerberos" for t in tried):
            error_msg = (
                f"Kerberos fallito: {error_msg}. "
                "Verifica che il DC sia raggiungibile, le credenziali siano nel formato user@DOMAIN.FQDN, "
                "e che krb5.conf sia configurato correttamente."
            )
        elif _is_credssp_unavailable(error_msg) or (
            "negotiate" in err_lower and "kerberos" in err_lower
        ):
            krb_hint = ""
            if not kerberos_ready:
                krb_hint = (
                    " Kerberos auto-kinit non riuscito — verifica che le credenziali siano "
                    "in formato user@DOMAIN.FQDN e che il DC sia raggiungibile sulla porta 88."
                )
            error_msg = (
                f"Windows WinRM accetta solo Kerberos (metodi: Negotiate, Kerberos). "
                f"Metodi tentati: {tried_str}.{krb_hint}"
                + _windows_winrm_config_hint()
            )
        elif (
            "401" in error_msg
            or "credentials were rejected" in err_lower
            or "authorization failed" in err_lower
            or "access is denied" in err_lower
            or "logon failure" in err_lower
        ):
            error_msg = (
                f"Credenziali rifiutate da Windows (WinRM) con {tried_str}. "
                "Verifica password e formato utente: "
                "in Active Directory usa utente@dominio.fqdn (consigliato per Kerberos); "
                "per NTLM anche DOMINIO\\\\utente; "
                "per account locale usa .\\\\utente o NOMEPC\\\\utente. "
                "L'utente deve essere membro di 'Utenti gestione remota' o Administrators. "
                "Controlla che l'account non sia bloccato/scaduto."
            )
        elif _is_basic_unavailable(error_msg):
            error_msg = (
                "Basic auth rifiutata (AllowUnencrypted=false o Basic non abilitato). "
                + _windows_winrm_config_hint()
            )
        elif "ECONNREFUSED" in error_msg or "Connection refused" in error_msg or "refused" in err_lower:
            error_msg = (
                "Connessione rifiutata: WinRM non in ascolto o firewall. Sul Windows: "
                "winrm quickconfig; apri porta 5985 (HTTP) o 5986 (HTTPS) verso l'IP del server DA-INVENT."
            )
        elif "timed out" in err_lower or "timeout" in err_lower:
            error_msg = f"Timeout connessione WinRM a {host}:{port}. Metodi tentati: {tried_str}."
        else:
            error_msg = f"Errore WinRM ({tried_str}): {error_msg}"

        print(json.dumps({"error": error_msg}))
        sys.exit(1)


if __name__ == "__main__":
    main()
